### ISSUE TITLE
Checker pieces don't always move to the square the player clicks on

### ISSUE THREAD

**Issue by cfcrawford** [mcheng09/Classic-Checkers#1]
The playing field design looks good, but sometimes the pieces will highlight the possible spaces but won’t allow the player to move to it when clicked, so make sure the piece can move to the available spaces each time.

**Comment by mcheng09** [comment]
Thanks for your input. I have fixed it so that you are able to move the first row of pieces and unable to move any of the other pieces behind. Will fix the new issues.
