### ISSUE TITLE
after red or black move, make white cell unselectable, make new cell selectable

### ISSUE THREAD

**Issue by benhulan** [mcheng09/Classic-Checkers#5]
event listeners are on white cells, not pieces. pieces are a background image of a class. need if logic to determine whether white cell has redPiece or blackPiece class before adding listeners

**Comment by mcheng09** [comment]
Hey Ben! Finally touching up on all my project and determined to complete this one! Was able to fix all the logic for moving pieces. Now just need to work on jumping, kinging and scoreboard! Thanks for the issue.
